# Netlify config for Vite frontend
[build]
  command = "npm run build"
  publish = "dist"

# You can set environment variables in Netlify UI (recommended) or here per-context.
# [build.environment]
#   VITE_API_BASE = "https://your-backend.example.com"
#   VITE_FIREBASE_API_KEY = "..."
