export const RECOMMENDED_SKILLS = [
  "Python",
  "JavaScript",
  "TypeScript",
  "React",
  "Next.js",
  "Node.js",
  "Express",
  "Java",
  "C++",
  "SQL",
  "NoSQL",
  "MongoDB",
  "PostgreSQL",
  "AWS",
  "GCP",
  "Docker",
  "Kubernetes",
  "Git",
  "HTML",
  "CSS",
  "Tailwind",
  "Machine Learning",
  "Deep Learning",
  "NLP",
  "Data Structures",
  "Algorithms",
  "DSA",
  "REST APIs",
  "GraphQL",
  "Firebase",
  "React Native",
  "Figma",
];

export const RECOMMENDED_INTERESTS = [
  "Software Engineering",
  "Frontend",
  "Backend",
  "Fullstack",
  "AI/ML",
  "Data Science",
  "Cloud",
  "Cybersecurity",
  "DevOps",
  "Mobile Apps",
  "Web3",
  "Open Source",
  "Startups",
];

export const RECOMMENDED_ROLES = [
  "Software Engineer Intern",
  "Frontend Developer Intern",
  "Backend Developer Intern",
  "Fullstack Developer Intern",
  "Data Science Intern",
  "Machine Learning Intern",
  "Cloud Intern",
  "DevOps Intern",
  "Mobile Developer Intern",
  "Product Intern",
];

export const RECOMMENDED_LOCATIONS = [
  "Remote",
  "India",
  "Bengaluru",
  "Hyderabad",
  "Delhi NCR",
  "Pune",
  "Mumbai",
  "Chennai",
];
