branch-defaults:
  main:
    environment: studentpilot-backend-env
    group_suffix: null
environment-defaults:
  studentpilot-backend-env:
    branch: null
    repository: null
global:
  application_name: studentpilot-backend
  default_ec2_keyname: null
  default_platform: Docker
  default_region: ap-south-1
  sc: git
