name: Deploy Backend to Elastic Beanstalk

on:
  push:
    branches: [ "main" ]
    paths:
      - "backend/**"
      - ".github/workflows/deploy-eb.yml"

jobs:
  deploy:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: backend
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Guard: no legacy EB options
        run: |
          echo "Scanning for forbidden ContainerPort / aws:elasticbeanstalk:container:docker options"
          if grep -R "aws:elasticbeanstalk:container:docker" -n .ebextensions || grep -R "ContainerPort" -n .ebextensions; then
            echo "Found legacy docker namespace or ContainerPort; fail." >&2
            exit 1
          fi
          echo "Guard passed."

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Create environment if missing
        run: |
          ENV_NAME=studentpilot-backend-env
          if ! eb status "$ENV_NAME" >/dev/null 2>&1; then
            eb create "$ENV_NAME" --single --platform "Docker" --cname "$ENV_NAME"
          fi

      - name: Set/refresh env vars
        run: |
          eb use studentpilot-backend-env
          eb setenv PORT=8000 WORKERS=2 TIMEOUT=120

      - name: Deploy
        env:
          GITHUB_SHA: ${{ github.sha }}
          GITHUB_RUN_NUMBER: ${{ github.run_number }}
        run: |
          LABEL="build-${GITHUB_RUN_NUMBER}-${GITHUB_SHA::7}"
          echo "LABEL=$LABEL"
          eb deploy --label "$LABEL" --staged

      - name: Smoke test
        run: |
          ENV_NAME=studentpilot-backend-env
          CNAME=$(eb status "$ENV_NAME" | awk '/CNAME:/ {print $2}')
          echo "CNAME=$CNAME"
          curl -fsS http://$CNAME/health || (echo "Health failed" && exit 1)
          curl -s -X POST http://$CNAME/api/search -H 'Content-Type: application/json' -d '{"query":"software","location":"","mode":"","min_stipend":0,"skills":[],"domains":[]}' | head -c 300 || true

# This file is intentionally disabled to avoid duplicate deployments.
# Canonical workflow: .github/workflows/deploy-backend.yml
# Left in repo so former references don't cause confusion. Will never run.

on:
  push:
    branches: [ __never_run__ ]
  workflow_dispatch: {}

jobs:
  noop:
    runs-on: ubuntu-latest
    steps:
      - run: echo "This legacy workflow is disabled. Use deploy-backend.yml instead."
