name: DISABLED legacy EB workflow (do not use)

# This file is intentionally disabled to avoid duplicate deployments.
# Canonical workflow: .github/workflows/deploy-backend.yml
# Left in repo so former references don't cause confusion. Will never run.

on:
  push:
    branches: [ __never_run__ ]
  workflow_dispatch: {}

jobs:
  noop:
    runs-on: ubuntu-latest
    steps:
      - run: echo "This legacy workflow is disabled. Use deploy-backend.yml instead."
